@Assets.API_HostAddress = https://localhost:7270


// Assets
###

GET {{Assets.API_HostAddress}}/api/assets

###


GET {{Assets.API_HostAddress}}/api/assets/1

###

POST {{Assets.API_HostAddress}}/api/assets
Content-Type: application/json

{
  "Name": "Drago Zakopane House",
  "Description": "Modern house with beautiful interior, ideal for those who appreciate modernity and comfort. It is located in the prestigious neighborhood of Birch Meadow, offering peace and comfort.",
   "Category": "House",
   "City": "London",
   "Street": "Cork St 5",
   "PostalCode": "10-100",
   "Space": 250
}

###

PATCH {{Assets.API_HostAddress}}/api/assets/1
Content-Type: application/json

{
   "Name": "Drago Castle",
   "Description": "Modern house with beautiful interior, ideal for those who appreciate modernity and comfort",
   "Space": 200
}

###

// Authentication
POST {{Assets.API_HostAddress}}/register
Content-Type: application/json

{
    "email": "testuser@test.gmail",
    "password": "Password1$"
}
###

POST {{Assets.API_HostAddress}}/login
Content-Type: application/json

{
    "email": "testuser@test.gmail",
    "password": "Password1$"
}


// Materials
### 
POST {{Assets.API_HostAddress}}/api/assets/11/dishes
Content-Type: application/json

{
  "name": "drewo",
  "description": "Wood is a structural tissue found in the stems and roots of trees and other woody plants. It is an organic materia",
  "price": 150,
  "origin": "europe"
}