@Assets_API_HostAddress = https://localhost:7270
@token = CfDJ8Et0ELM66M1HpWgm4Itvsa2LdfPWixyIGrzMVweBy-bO1s77s78bcJBcp-FLLVM30etjLhgjI1Z5ZC4JLSxKK06VAegbOdaSvCZ1ttfY8irmT6UF6e2z4A0gHwiOLWjUs84nv7gc102L3lp6drvJo7bGFq5He5xZH4aw5eN_Bi0QNy38HvRwn2r8vY-bChLTAoZrOUkzzl4JEO2VVX-Brqe9cEr8WbpVwlxfWxVz7w-OmXbIM5b4Hy-ofcJ5w8nvM7uvWAG8AIhDsQX7T4ilR2qQGLLRvUs_jvi-qmZIFsKuhmA30rpnYSRHibKPyHBsemoo5opOg96nbZUEbgr0C4orysNQNRq1BEEO5mNXuy3FsiFod2ErrIOiex4B4BRhRBbAh2lKwVdtPRJNaBaBlNKnOlTxYaMRK4M9rhzUPb1hEWZ9F1-chsa3L5b-zz5pSak5ngHiGYurlIi2MeUwmwPcvXEBEUblaiyn-qqVFmxFL0FKH62roSuZgBvo0aMuM1RmHS5zajVqIs03v6goTB5rm1r_-ut_2yAvddQO_WE54rFp6LJwFf-semIfmxdCkUoDCaomrNTSBUSn4vRwR7rD6a5UXov3WFHN-7toSjr56qi04wsFIlMDq7rbB1hM34KfA4mev05Vnwv4fjX3t8udWR8o9xEM2vUEYpaL_YTQM1KfCGAWu6oSzR_dYNSR0XzrC084eqyBdxkgPsbja8k

// Assets
GET {{Assets_API_HostAddress}}/api/assets
Authorization: Bearer {{token}}

###
GET {{Assets_API_HostAddress}}/api/assets/1002
Authorization: Bearer {{token}}

###
POST {{Assets_API_HostAddress}}/api/assets
Content-Type: application/json

{
  "Name": "Drago Zakopane House",
  "Description": "Modern house with beautiful interior, ideal for those who appreciate modernity and comfort. It is located in the prestigious neighborhood of Birch Meadow, offering peace and comfort.",
   "Category": "House",
   "City": "London",
   "Street": "Cork St 5",
   "PostalCode": "10-100",
   "Space": 250
}
###

PATCH {{Assets_API_HostAddress}}/api/assets/1
Content-Type: application/json

{
   "Name": "Drago Castle",
   "Description": "Modern house with beautiful interior, ideal for those who appreciate modernity and comfort",
   "Space": 200
}

###

// Authentication
POST {{Assets_API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "owner@test.gmail",
    "password": "Password1$"
}
###

POST {{Assets_API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "testuser@test.gmail",
    "password": "Password1$"
}


###
// Materials
POST {{Assets_API_HostAddress}}/api/assets/1002/materials
Content-Type: application/json

{
  "name": "wood",
  "description": "Wood is a structural tissue found in the stems and roots of trees and other woody plants. It is an organic materia",
  "price": 300,
  "origin": "europe"
}


###
GET {{Assets_API_HostAddress}}/api/assets/1002/materials

###
GET {{Assets_API_HostAddress}}/api/assets/1002/materials/1005

###

DELETE {{Assets_API_HostAddress}}/api/assets/1002/materials/1007

###
PATCH {{Assets_API_HostAddress}}/api/assets/1002/materials/1009
Content-Type: application/json

{
  "name": "wood",
  "description": "Elegancki Update",
  "price": 500,
  "origin": "europe"
}