@Assets_API_HostAddress = https://localhost:7270


// Assets
GET {{Assets_API_HostAddress}}/api/assets

###
GET {{Assets_API_HostAddress}}/api/assets/1002


###
POST {{Assets_API_HostAddress}}/api/assets
Content-Type: application/json

{
  "Name": "Drago Zakopane House",
  "Description": "Modern house with beautiful interior, ideal for those who appreciate modernity and comfort. It is located in the prestigious neighborhood of Birch Meadow, offering peace and comfort.",
   "Category": "House",
   "City": "London",
   "Street": "Cork St 5",
   "PostalCode": "10-100",
   "Space": 250
}
###

PATCH {{Assets_API_HostAddress}}/api/assets/1
Content-Type: application/json

{
   "Name": "Drago Castle",
   "Description": "Modern house with beautiful interior, ideal for those who appreciate modernity and comfort",
   "Space": 200
}

###

// Authentication
POST {{Assets_API_HostAddress}}/register
Content-Type: application/json

{
    "email": "testuser@test.gmail",
    "password": "Password1$"
}
###

POST {{Assets_API_HostAddress}}/login
Content-Type: application/json

{
    "email": "testuser@test.gmail",
    "password": "Password1$"
}


###
// Materials
POST {{Assets_API_HostAddress}}/api/assets/1002/materials
Content-Type: application/json

{
  "name": "wood",
  "description": "Wood is a structural tissue found in the stems and roots of trees and other woody plants. It is an organic materia",
  "price": 300,
  "origin": "europe"
}


###
GET {{Assets_API_HostAddress}}/api/assets/1002/materials

###
GET {{Assets_API_HostAddress}}/api/assets/1002/materials/1005

###

DELETE {{Assets_API_HostAddress}}/api/assets/1002/materials/1007

###
PATCH {{Assets_API_HostAddress}}/api/assets/1002/materials/1009
Content-Type: application/json

{
  "name": "wood",
  "description": "Elegancki Update",
  "price": 500,
  "origin": "europe"
}